# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gje1_M-SOF3S0O7B_ODb-ff0UmzyFMiH
"""

#Primero preferí crear una función para cada opción del menú en el que se modificará el archivo de texto.
def leer_archivo(nombre_archivo):
    try:
        with open(nombre_archivo, 'r') as archivo:
            contenido = archivo.read()
            print(contenido)
    except FileNotFoundError:
        print(f"El archivo '{nombre_archivo}' no se encontró.")

def escribir_archivo(nombre_archivo):
    contenido = input("Ingresa el contenido que deseas escribir en el archivo: ")
    with open(nombre_archivo, 'w') as archivo:
        archivo.write(contenido)
    print(f"Se ha escrito el contenido en el archivo '{nombre_archivo}'.")

def modificar_archivo(nombre_archivo):
    try:
        with open(nombre_archivo, 'r+') as archivo:
            contenido_original = archivo.read()
            print("Contenido original del archivo:")
            print(contenido_original)

            nuevo_contenido = input("Ingresa el nuevo contenido: ")
            archivo.seek(0)  # Volver al principio del archivo
            archivo.write(nuevo_contenido)
            archivo.truncate()  # Eliminar el contenido sobrante

            print(f"El archivo '{nombre_archivo}' ha sido modificado.")
    except FileNotFoundError:
        print(f"El archivo '{nombre_archivo}' no se encontró.")

#Se imprime un menú con while para que el usuario pueda hacer varias acciones una después de la otra, o dejar el archivo.
while True:
    print("\nMenú:")
    print("1. Leer archivo")
    print("2. Escribir archivo")
    print("3. Modificar archivo")
    print("4. Salir")

    opcion = input("Selecciona una opción: ")

    if opcion == '1':
        nombre_archivo = input("Ingresa el nombre del archivo: ")
        leer_archivo(nombre_archivo)
    elif opcion == '2':
        nombre_archivo = input("Ingresa el nombre del archivo: ")
        escribir_archivo(nombre_archivo)
    elif opcion == '3':
        nombre_archivo = input("Ingresa el nombre del archivo: ")
        modificar_archivo(nombre_archivo)
    elif opcion == '4':
        break
    else:
        print("Opción inválida. Por favor, selecciona una de las opciones mostradas.")

